import type { Question } from "./types";

const q = (text: string, options: string[], answer: number): Question => ({ text, options, answer });

export const FALLBACK_BANK: Question[] = [
  q("On which date is Indian Air Force Day celebrated every year?", ["1 August", "15 August", "8 October", "26 January"], 2),
  q("In which year was the Indian Air Force established?", ["1932", "1947", "1950", "1962"], 0),
  q("What is the motto of the Indian Air Force?", ["Service Before Self", "Touch the Sky with Glory", "Victory Through Valour", "Guardians of the Nation"], 1),
  q("Who was the first Indian Chief of the Air Staff?", ["Arjan Singh", "Subroto Mukerjee", "P. C. Lal", "Idris Hasan Latif"], 1),
  q("Who is the only IAF officer to have attained the rank of Marshal of the Indian Air Force?", ["Arjan Singh", "Subroto Mukerjee", "Om Prakash Mehra", "Dilbagh Singh"], 0),
  q("Which IAF officer is the only airman to have received the Param Vir Chakra?", ["Abhinandan Varthaman", "Nirmal Jit Singh Sekhon", "Ajay Ahuja", "Rakesh Sharma"], 1),
  q("Which air operation was carried out by the IAF during the 1999 Kargil conflict?", ["Operation Vijay", "Operation Meghdoot", "Operation Safed Sagar", "Operation Cactus"], 2),
  q("Which company manufactures the Rafale fighter aircraft operated by the IAF?", ["Lockheed Martin", "Dassault Aviation", "Sukhoi", "Eurofighter GmbH"], 1),
  q("Which public-sector company manufactures the Tejas light combat aircraft?", ["Bharat Electronics Limited", "Bharat Dynamics Limited", "Mishra Dhatu Nigam", "Hindustan Aeronautics Limited"], 3),
  q("The Sukhoi Su-30MKI was originally developed in which country?", ["France", "United States", "Russia", "Sweden"], 2),
  q("Which IAF pilot became the first Indian to travel to space, in 1984?", ["Rakesh Sharma", "Kalpana Chawla", "Sunita Williams", "Ravish Malhotra"], 0),
  q("Wing Commander Abhinandan Varthaman was flying which aircraft when he was shot down in February 2019?", ["Mirage 2000", "MiG-21 Bison", "Jaguar", "Su-30MKI"], 1),
  q("Which aircraft did the IAF use in the Balakot air strike of February 2019?", ["MiG-29", "Mirage 2000", "Tejas", "Hawk"], 1),
  q("Where is the Indian Air Force Academy located?", ["Pune", "Bengaluru", "Dundigal, near Hyderabad", "Nagpur"], 2),
  q("Which IAF rank is equivalent to a Colonel in the Indian Army?", ["Wing Commander", "Group Captain", "Squadron Leader", "Air Commodore"], 1),
  q("What is the highest serving rank in the IAF in peacetime?", ["Marshal of the Indian Air Force", "Air Marshal", "Air Chief Marshal", "Air Vice Marshal"], 2),
  q("Which IAF aerobatic display team flies the Hawk Mk 132 jet trainers?", ["Sarang", "Suryakiran", "Akash Ganga", "Vajra"], 1),
  q("The IAF's Sarang helicopter display team flies which helicopter?", ["Mi-17", "Chetak", "Apache", "HAL Dhruv"], 3),
  q("Which company manufactures the C-17 Globemaster III used by the IAF for strategic airlift?", ["Airbus", "Boeing", "Ilyushin", "Embraer"], 1),
  q("The Apache AH-64E and Chinook CH-47F helicopters in IAF service are built by which company?", ["Boeing", "Airbus", "Leonardo", "Sikorsky"], 0),
  q("Which IAF officer travelled to the International Space Station in 2025 on the Axiom-4 mission?", ["Prashanth Nair", "Ajit Krishnan", "Shubhanshu Shukla", "Angad Pratap"], 2),
  q("In 1988, Operation Cactus saw the IAF airlift paratroopers to help which country?", ["Sri Lanka", "Maldives", "Nepal", "Seychelles"], 1),
  q("Which missile can the Su-30MKI carry in its air-launched version, developed jointly by India and Russia?", ["Agni-V", "BrahMos", "Prithvi", "Nag"], 1),
  q("What is the name of the IAF's special forces unit?", ["MARCOS", "Para SF", "Garud Commando Force", "NSG"], 2),
  q("Where is the Southern Air Command of the IAF headquartered?", ["Chennai", "Thiruvananthapuram", "Bengaluru", "Kochi"], 1),
  q("The Jaguar strike aircraft in IAF service was jointly developed by which two countries?", ["India and Russia", "France and Germany", "United Kingdom and France", "United States and Israel"], 2),
  q("Which small fighter was nicknamed 'Sabre Slayer' for its performance against Pakistan's F-86 Sabres in 1965?", ["Hunter", "Gnat", "Vampire", "Canberra"], 1),
  q("In which year was the Kargil conflict fought?", ["1971", "1999", "2001", "1965"], 1),
  q("Which 2025 operation saw Indian forces strike terrorist infrastructure after the Pahalgam attack?", ["Operation Rahat", "Operation Vijay", "Operation Meghdoot", "Operation Sindoor"], 3),
  q("By what name is the Mirage 2000 known in Indian Air Force service?", ["Garuda", "Shakti", "Vajra", "Trishul"], 2),
];
